[theme]
primaryColor = "#E30613"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1A1A1A"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
headless = true
